=== labra/ejemplosXML/pedido.dtd
<!ELEMENT pedido (producto)*>
<!ELEMENT producto (nombre, cantidad,comentarios, precio?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT comentarios (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST producto codigo CDATA #REQUIRED>
<!ATTLIST precio moneda CDATA #IMPLIED>

=== labra/ejemplosXML/pedido.xml
<!DOCTYPE pedido SYSTEM "pedido.dtd">
<pedido>
  <producto codigo="R23">
	<nombre>Rotulador RX2</nombre>
 	<cantidad>20</cantidad>
 	<comentarios>Comprobad que escriben</comentarios>

  </producto>
  <producto codigo="G56">
 	<nombre>Grapadora Lin</nombre>
 	<cantidad>2</cantidad>
	<comentarios>Envuelta para regalo</comentarios>
  </producto>
  <producto codigo="G78">
 	<nombre>Computadora Lenovo</nombre>
 	<cantidad>2</cantidad>
	<comentarios>Para el MTI 2016</comentarios>
	<precio moneda="Pesos chilenos">34000</precio>
  </producto>
</pedido>
